---
kypo_training_config_version: 1
training:
  id: techanalysissecmanage
  name: TechAnalysisSecManage
  description: >-
    Single-module training focused on Subcase 1c malware analysis and cyber threat intelligence
    (CTI) response workflows.
  modules:
    - id: subcase_1c_malware_cti
      name: Subcase 1c Malware & CTI Module
      description: >-
        Guided malware analysis and CTI exercises using the Subcase 1c lab assets.
      sandboxes:
        - id: subcase_1c  # see docs/subcase_1c_guide.md for deployment and validation steps
          topology: sandboxes/topology_subcase_1c.yaml
          provisioning: sandboxes/provisioning_subcase_1c/site.yml
