---
kypo_training_config_version: 1
training:
  id: techanalysissecmanage
  name: TechAnalysisSecManage
  description: >-
    Single-module training focused on Subcase 1c malware analysis and cyber threat intelligence
    (CTI) response workflows.
  modules:
    - id: subcase_1c_malware_cti
      name: Subcase 1c Malware & CTI Module
      description: >-
        Guided malware analysis and CTI exercises using the Subcase 1c lab assets.
      sandboxes:
        - id: subcase_1c
          definition: sandboxes/Sandbox Agenda/sandbox.yaml
        - id: sandbox_agenda
          definition: sandboxes/Sandbox Agenda/sandbox_agenda.yaml
