---
- hosts: infected-host
  become: yes
  tasks:
    - name: Install investigation tools
      apt:
        name:
          - tcpdump
          - powershell
        state: present

- hosts: c2-server
  become: yes
  tasks:
    - name: Start bundled C2 server
      ansible.builtin.script: "{{ playbook_dir }}/../../subcase_1c/scripts/start_c2-server.sh"

- hosts: soc-server
  become: yes
  tasks:
    - name: Install Docker engine for SOC services
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Launch SOC stack via startup script
      ansible.builtin.script: "{{ playbook_dir }}/../../subcase_1c/scripts/start_soc_services.sh"
      environment:
        MISP_API_KEY: "{{ lookup('env', 'MISP_API_KEY') | default('demo-misp-key', true) }}"

- hosts: cti-component
  become: yes
  tasks:
    - name: Start CTI component services
      ansible.builtin.script: "{{ playbook_dir }}/../../subcase_1c/scripts/start_cti-component.sh"
